<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="IBM141-PC0F1FB8" name="com.mendix.test.Vendor_JDE_Script" tests="2" failures="0" timestamp="12 Jun 2019 10:43:53 GMT" time="0.000" errors="2">
  <testcase name="Vendor_Create_Fill_In_Data_JDE_Local_Finance" time="0.000" classname="com.mendix.test.Vendor_JDE_Script">
    <error type="org.testng.TestNGException" message="
Method public void com.mendix.test.Vendor_JDE_Script.Vendor_Create_Fill_In_Data_JDE_Local_Finance(java.util.Map) throws java.lang.InterruptedException,java.io.FileNotFoundException,java.io.IOException,java.awt.AWTException requires a @DataProvider named : Vendor_Create_Global_Disable_Bank_and_LocalData in class com.mendix.util.DataProviderUtil$staticProviderClass">
      <![CDATA[org.testng.TestNGException: 
Method public void com.mendix.test.Vendor_JDE_Script.Vendor_Create_Fill_In_Data_JDE_Local_Finance(java.util.Map) throws java.lang.InterruptedException,java.io.FileNotFoundException,java.io.IOException,java.awt.AWTException requires a @DataProvider named : Vendor_Create_Global_Disable_Bank_and_LocalData in class com.mendix.util.DataProviderUtil$staticProviderClass
at org.testng.internal.Parameters.findDataProvider(Parameters.java:513)
at org.testng.internal.Parameters.handleParameters(Parameters.java:691)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Vendor_Create_Fill_In_Data_JDE_Local_Finance -->
  <testcase name="Vendor_Create_Fill_In_Data_JDE_Local_Purchasing" time="0.000" classname="com.mendix.test.Vendor_JDE_Script">
    <error type="org.testng.TestNGException" message="
Method public void com.mendix.test.Vendor_JDE_Script.Vendor_Create_Fill_In_Data_JDE_Local_Purchasing(java.util.Map) throws java.lang.InterruptedException,java.io.FileNotFoundException,java.io.IOException,java.awt.AWTException requires a @DataProvider named : Vendor_Create_Global_Disable_Bank_and_LocalData in class com.mendix.util.DataProviderUtil$staticProviderClass">
      <![CDATA[org.testng.TestNGException: 
Method public void com.mendix.test.Vendor_JDE_Script.Vendor_Create_Fill_In_Data_JDE_Local_Purchasing(java.util.Map) throws java.lang.InterruptedException,java.io.FileNotFoundException,java.io.IOException,java.awt.AWTException requires a @DataProvider named : Vendor_Create_Global_Disable_Bank_and_LocalData in class com.mendix.util.DataProviderUtil$staticProviderClass
at org.testng.internal.Parameters.findDataProvider(Parameters.java:513)
at org.testng.internal.Parameters.handleParameters(Parameters.java:691)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Vendor_Create_Fill_In_Data_JDE_Local_Purchasing -->
</testsuite> <!-- com.mendix.test.Vendor_JDE_Script -->
